Exercises XP
 Exercise 1 : Array Creation and Manipulation
 Create a 1D NumPy array containing numbers from 0 to 9.

In [9]:
import numpy as np
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

 Exercise 2 : Type Conversion and Array Operations
Instructions
Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

In [8]:
given_list = [3.14, 2.17, 0, 1, 2]
array_given_list = np.array(given_list, dtype=int)
array_given_list

array([3, 2, 0, 1, 2])

Exercise 3 : Working with Multi-Dimensional Arrays
Instructions
Create a 3x3 NumPy array with values ranging from 1 to 9.

Expected Output:

In [3]:
threebythree_array = np.arange(1, 10).reshape(3, 3)
threebythree_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers
Instructions
Create a 2D NumPy array of shape (4, 5) filled with random numbers.

In [4]:
array_random = np.random.rand(4, 5)
array_random

array([[0.61334401, 0.64493501, 0.68249041, 0.73567405, 0.28969754],
       [0.89996066, 0.97897495, 0.3594906 , 0.22562456, 0.08273691],
       [0.15238135, 0.88244069, 0.31670319, 0.52571283, 0.51358317],
       [0.88294891, 0.95527065, 0.81106667, 0.05136125, 0.75618798]])

 Exercise 5 : Indexing Arrays
Instructions
Select the second row from a given 2D NumPy array.

In [5]:
array_2d = np.array([[10, 11, 12, 13, 14],
                     [20, 21, 22, 23, 24],
                     [30, 31, 32, 33, 34]])
second_row = array_2d[1, :]
second_row

array([20, 21, 22, 23, 24])

🌟 Exercise 6 : Reversing elements
Instructions
Reverse the order of elements in a given 1D NumPy array (first element becomes last).

In [10]:
reversed_array = array[::-1]
reversed_array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

 Exercise 7 : Identity Matrix
Instructions
Create a 4x4 identity matrix using NumPy.

In [11]:
identity_matrix = np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Exercise 8 : Simple Aggregate Funcs
Instructions
Find the sum and average of a given 1D arra

In [13]:
sum_array = np.sum(array)
average_array = np.mean(array)
print(sum_array)
average_array

45


4.5

 Exercise 9 : Create Array and Change its Structure
Instructions
Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

In [15]:
one_to_twenty_array = np.arange(1, 21)
reshaped_array = one_to_twenty_array.reshape(4, 5)
reshaped_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

🌟 Exercise 10 : Conditional Selection of Values
Instructions
Extract all odd numbers from a given NumPy array.

In [17]:
odd_numbers = array[array % 2 == 1]
odd_numbers

array([1, 3, 5, 7, 9])