In [15]:
import numpy as np
import pandas as pd
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d)
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [3]:
type(array_1d)
print(type)

<class 'numpy.ndarray'>


In [7]:
a = 3.0
if a == int(a):
    print(int(a))
else:
    print("a is not an integer")

3


In [8]:
temps = np.array([30, 32, 31, 29, 28, 27, 26, 25, 24, 26, 28, 30, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,41, 42, 43, 44, 45, 46, 47, 48,47,56,54])
len(temps)

32

NameError: name 'ADD' is not defined

In [16]:
sales_data = pd.DataFrame({
    "Monday": [200, 150, 100, 300, 50],
    "Tuesday": [220, 160, 110, 320, 60],
    "Wednesday": [250, 180, 120, 340, 70],
    "Thursday": [270, 200, 130, 360, 80],
    "Friday": [300, 210, 140, 400, 90],
    "Saturday": [310, 220, 150, 420, 100],
    "Sunday": [280, 190, 160, 410, 110]
}, index=["Store 1", "Store 2", "Store 3", "Store 4", "Store 5"])
print("Sales Data (Pandas DataFrame):\n", sales_data)

Sales Data (Pandas DataFrame):
          Monday  Tuesday  Wednesday  Thursday  Friday  Saturday  Sunday
Store 1     200      220        250       270     300       310     280
Store 2     150      160        180       200     210       220     190
Store 3     100      110        120       130     140       150     160
Store 4     300      320        340       360     400       420     410
Store 5      50       60         70        80      90       100     110


In [18]:
sales_array = sales_data.to_numpy()
np.save('sales_data.npy', sales_array)
print("Sales Data (NumPy Array):\n", sales_array)

Sales Data (NumPy Array):
 [[200 220 250 270 300 310 280]
 [150 160 180 200 210 220 190]
 [100 110 120 130 140 150 160]
 [300 320 340 360 400 420 410]
 [ 50  60  70  80  90 100 110]]


In [19]:

daily_sales = sales_array.sum(axis=0)

# Step 3: Find the days where the total sales are greater than 1200
days_above_1200 = daily_sales[daily_sales > 1200]

# Step 4: Display the result
days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
result_days = [days[i] for i in range(len(daily_sales)) if daily_sales[i] > 1200]

print("Days with sales greater than 1200:", result_days)


Days with sales greater than 1200: []


In [21]:
store_4_sales = sales_array[3,sales_array[3] > 350]
print("Sales Data for Store 4:\n", store_4_sales)

Sales Data for Store 4:
 [360 400 420 410]


In [23]:
days_above_350 = np.where(sales_array > 350)[0]
print("Days with sales greater than 350:\n", days_above_350)

Days with sales greater than 350:
 [3 3 3 3]


In [24]:
days_names = sales_array.columns[days_above_350].tolist()
print("Days with sales greater than 350:\n", days_names)

AttributeError: 'numpy.ndarray' object has no attribute 'columns'